spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emergency_db
    username: postgres                    
    password: Daniyar
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update  # ИЗМЕНИТЬ на update после первого запуска
    show-sql: true                       
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    
  cache:
    type: simple

jwt:
  secret: "bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA="
  access-cookie-name: "access_token"
  refresh-cookie-name: "refresh_token"

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.example.demo: INFO
    org.springframework.security: INFO